name: Greetings

on:
  pull_request_target:
    types: [opened, reopened, closed]
  issues:
    types: [opened, closed]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our DDoL team will review it shortly. Stay tuned!"
          pr-message: "🎉 Thank you for your contribution! Your pull request has been submitted successfully. A maintainer from DDoL team will review it as soon as possible. We appreciate your support in making this project better."

  congratulate:
    if: github.event.action == 'closed' && github.event.issue != null
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment on the closed issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;
            const message = `
              🎉 Congratulations on closing the issue! Thank you for your contribution to the project. 
              If you enjoy working with us, consider giving us a star on GitHub ⭐ and following us on our socials!
            `;
            await github.issues.createComment({
              ...context.repo,
              issue_number: issueNumber,
              body: message,
            });
